# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: "pip"          # works with Poetry via poetry.lock
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "click"      # keep Typer-compatible
        versions: [">=8.2"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"