name: Build and push Docker image

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      push:
        description: 'Push images to registries'
        required: true
        default: 'false'
        type: choice
        options: ['false', 'true']

env:
  # Push to both Docker Hub and GHCR
  IMAGE_NAMES: |
    docker.io/asvarnon/apicache
    docker.io/${{ github.repository_owner }}/apicache
    ghcr.io/${{ github.repository_owner }}/apicache

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAMES }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      # Skip login on PRs and on Dependabot pushes
      - name: Login to Docker Hub
        if: |
          (github.event_name == 'push' && github.actor != 'dependabot[bot]' && !startsWith(github.ref, 'refs/heads/dependabot/')) ||
          (github.event_name == 'workflow_dispatch' && inputs.push == 'true')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        if: |
          (github.event_name == 'push' && github.actor != 'dependabot[bot]' && !startsWith(github.ref, 'refs/heads/dependabot/')) ||
          (github.event_name == 'workflow_dispatch' && inputs.push == 'true')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and (optionally) push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ (github.event_name == 'push' && github.actor != 'dependabot[bot]' && !startsWith(github.ref, 'refs/heads/dependabot/')) || (github.event_name == 'workflow_dispatch' && inputs.push == 'true') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}