name: pip-audit
on:
#   schedule:
#     - cron: "0 9 * * 1"   # Mondays 09:00 UTC
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install tools
        run: |
          python -m pip install --upgrade pip pip-audit poetry
      - name: Export dependencies
        run: |
          poetry export -f requirements.txt --without-hashes -o req.txt
      - name: Run pip-audit
        run: |
          pip-audit -r req.txt